AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01a00762f46d584a1
      InstanceType: t3.micro
      Tags:
        - Key: Name
          Value: MyDemoInstance
